const TestimonialApi = [
    {
      id: 1,
      image: "https://media-exp1.licdn.com/dms/image/C4E03AQHzyxPY-zWJoQ/profile-displayphoto-shrink_200_200/0/1650622538355?e=1657152000&v=beta&t=zbPAc8c1g59k9lzQ120emHjn3OGT_J7LXtIo2_Xbn68",
      design: "Carte Visite",
      name: "Babacar Niang Fall",
      offcer: "Apprenant",
      post: "Developpeur Web et Mobile",
      date: "24 decembre - 26 decembre 2021",
      desc: "Seck  la cate Visite est trés jolie je suis vraiment content",
    },
    {
      id: 2,
      image: "https://media-exp1.licdn.com/dms/image/C4D03AQH2cqEBatxoFA/profile-displayphoto-shrink_200_200/0/1632264064545?e=1657152000&v=beta&t=6rCUgf3ePUQfyJLkUU_Vp0uJBS2ACcWfVAalgPB5wfQ",
      design: "Logo",
      name: "Djiby Seck",
      offcer: "Chef de Projet En Sytéme & Réseau ",
      post: "Responsable en Réseau Informatique",
      date: "10 novembre - 22 novembre 2021",
      desc: "Merci Beaucoup ,super mais joue encore sur la taille,sur l'arrière plan et la forme.",
    },
    {
      id: 3,
      image: "https://media-exp1.licdn.com/dms/image/C4D03AQFYJ9mc0p5EdQ/profile-displayphoto-shrink_200_200/0/1617439186648?e=1657152000&v=beta&t=G4uFtwhaJtXlOJfG6xsQgEPG4zwZmBJIAxxQlb98sqI",
      design: "Exposée HTML.CSS&JS",
      name: "Assane Gueye",
      offcer: "Choachs",
      post: "Choachs Development Web&Mobile",
      date: "29 avril 2022 à Edep",
      desc: "Seck vous avez fait un bon boulot et vous m'avais appris aussi des choses sur le Html Css ainsi que le javasript .Il faut juste améliorer certain chose mais en tout cas je vous encourage bien de votre courage ,il faut continuer sur ce lancer",
    },
    // {
    //   id: 4,
    //   image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFvrvXeMRAS2mH-vdnjuvs8zy-b7dsc7Z9xemfb785oa3leHq5ByslSAlviAzVZMbUoBA&usqp=CAU",
    //   design: "Bound - Trolola",
    //   name: "Jone Duone Joe",
    //   offcer: "Operating Officer",
    //   post: "Web App Development",
    //   date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
    //   desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
    // },
    // {
    //   id: 5,
    //   image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4fTdnGPV55B_0LbyeoTrietcQKf3S91AmFWG1_ucJGzffT58y4IWVhI7c4ANQh9V8SBo&usqp=CAU",
    //   design: "Glassfisom",
    //   name: "Nevine Dhawan",
    //   offcer: "CEO Of Officer",
    //   post: "Android App Design",
    //   date: "Fiver - Mar 4, 2015 - Aug 30, 2021",
    //   desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris	.",
    // },
  ]
  
  export default TestimonialApi
  